export const GET_THEME_SUCCESS = "GET_THEME_SUCCESS";
export const GET_THEME_ERROR = "GET_THEME_ERROR";

export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_ERROR = "GET_POSTS_ERROR";

export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_ERROR = "GET_COMMENT_ERROR";
